import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* === CSS: Esconde barra, mas mantém scroll funcional === */}
        <style>{`
          .no-visible-scrollbar {
            -ms-overflow-style: none;     /* IE and Edge */
            scrollbar-width: none;        /* Firefox */
          }
          .no-visible-scrollbar::-webkit-scrollbar {
            display: none !important;     /* Chrome, Safari, Opera */
            width: 0 !important;
            height: 0 !important;
          }
          .no-visible-scrollbar {
            overflow: auto !important;
            -webkit-overflow-scrolling: touch;
          }
        `}</style>

        {/* === JS: Comunicação com o iframe pai === */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Domínios permitidos do pai
                const allowedOrigins = [
                  'https://ctasalvador.com.br',
                  'http://localhost:8080'  // Dev
                ];

                window.addEventListener('message', (event) => {
                  if (!allowedOrigins.includes(event.origin)) return;

                  if (event.data === 'HIDE_SCROLLBAR') {
                    document.documentElement.classList.add('no-visible-scrollbar');
                  }
                  if (event.data === 'SHOW_SCROLLBAR') {
                    document.documentElement.classList.remove('no-visible-scrollbar');
                  }
                });

                // Só envia IFRA ME_READY se estiver dentro de um iframe
                if (window.parent !== window) {
                  window.parent.postMessage('IFRAME_READY', event.origin);
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased font-nunito`}>
        {children}
      </body>
    </html>
  );
}
