import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"], // All Nunito weights
  style: ["normal", "italic"], // Include both normal and italic styles
  display: "swap", // Improves FOUT
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          .no-visible-scrollbar {
            -ms-overflow-style: none;  /* IE and Edge */
            scrollbar-width: none;     /* Firefox */
          }
          .no-visible-scrollbar::-webkit-scrollbar {
            display: none !important;  /* Chrome, Safari, Opera */
            width: 0 !important;
            height: 0 !important;
          }
          /* Allow scrolling with mouse wheel and touch */
          .no-visible-scrollbar {
            -webkit-overflow-scrolling: touch;
            overflow: auto !important;
          }
        `}</style>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Escuta comandos do pai
              window.addEventListener('message', (event) => {
                // Segurança: só aceita do domínio do pai (ajuste para o seu domínio real)
                if (event.origin !== window.location.origin && event.origin !== 'http://localhost:3000') return; // Exemplo: permita localhost para dev

                if (event.data === 'HIDE_SCROLLBAR') {
                  document.documentElement.classList.add('no-visible-scrollbar');
                }
                if (event.data === 'SHOW_SCROLLBAR') {
                  document.documentElement.classList.remove('no-visible-scrollbar');
                }
              });

              // Notifica o pai quando estiver pronto
              if (window.parent !== window) {
                window.parent.postMessage('IFRAME_READY', '*');
              }
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased font-nunito`}>
        {children}
      </body>
    </html>
  );
}
